#:schema node_modules/wrangler/config-schema.json
name = "worker-a"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
[[services]]
binding = "WORKER_B"
service = "worker-b"
entrypoint = "WorkerBEntrypoint"
